### ISSUE TITLE
Test connection on a newly added database fails

### ISSUE THREAD

**Issue by dennisobrien** [airbnb/caravel#1167]
(I introduced this bug so I'll submit a PR shortly.)

When you click to add a new record in '/databaseview/list', then define a database name and provide a SQLAlchemy URI, then click TEST CONNECTION, the test fails and an exception is shown in a dialog:

```
database-name says:

ERROR: Traceback (most recent call last):
  File "/home/caravel/caravel_src/caravel/views.py", line 1283, in testconn
    if uri == database.save_sqlalchemy_uri():
  AttributionError: 'NoneType' object has no attribute 'save_sqlalchemy_uri'
```

The fix is for `testconn` to just use the sqlalchemy_uri passed in the request if the database name is not found in the db.

This is building off master commit 1ce8acc

**Comment by dennisobrien** [comment]
For the record, this was a regression I introduced with PR #1137
