### ISSUE TITLE
'Babel' object has no attribute 'translation_directories'

### ISSUE THREAD

**Issue by gbrian** [airbnb/caravel#847]
Hi there,
Has this happened to any of you?

`'Babel' object has no attribute 'translation_directories'`

What drives me crazy is I can't see where the babel extension is initialized:
`app.extensions['babel'] = self`
It's supposed to be managed by Babel __init__ ...but no way to debug stop there.

Environment Windows 7 . recently installed in a Ubuntu without any issue.

Thanks

**Comment by gbrian** [comment]
Packages version conflicts, sorry my fault!
Solved by reinstalling all "flask" related packages

**Comment by BGraco** [comment]
I am the exact same issue when updating Flask-Babel from 0.9 to 0.11.1.

I have been looking for any sort of documentation that indicates what flask extensions have compatibility with one another, is it just assumed that the minor version (major.minor.build) must match to be compatible?

Here are my current application versions that are having the issue:

Babel (2.3.4)
Flask (0.11.1)
Flask-Babel (0.11.1)
Flask-BabelEx (0.9.3)
Flask-Compress (1.3.2)
Flask-Login (0.4.0)
itsdangerous (0.24)
Jinja2 (2.8)
MarkupSafe (0.23)
pytz (2016.7)
setuptools (28.8.0)
speaklater (1.3)
Werkzeug (0.11.11)

**Comment by mistercrunch** [comment]
@BGraco are you on windows as well?

**Comment by BGraco** [comment]
I am on Debian 7, armhf

**Comment by BGraco** [comment]
I also opened up an issue under flask-babel as I am thinking this is a lower level issue. [https://github.com/python-babel/flask-babel/issues/111](url)
